// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package protob

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StringValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringValue) Reset()         { *m = StringValue{} }
func (m *StringValue) String() string { return proto.CompactTextString(m) }
func (*StringValue) ProtoMessage()    {}
func (*StringValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *StringValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringValue.Unmarshal(m, b)
}
func (m *StringValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringValue.Marshal(b, m, deterministic)
}
func (m *StringValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringValue.Merge(m, src)
}
func (m *StringValue) XXX_Size() int {
	return xxx_messageInfo_StringValue.Size(m)
}
func (m *StringValue) XXX_DiscardUnknown() {
	xxx_messageInfo_StringValue.DiscardUnknown(m)
}

var xxx_messageInfo_StringValue proto.InternalMessageInfo

func (m *StringValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BooleanValue struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BooleanValue) Reset()         { *m = BooleanValue{} }
func (m *BooleanValue) String() string { return proto.CompactTextString(m) }
func (*BooleanValue) ProtoMessage()    {}
func (*BooleanValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *BooleanValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BooleanValue.Unmarshal(m, b)
}
func (m *BooleanValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BooleanValue.Marshal(b, m, deterministic)
}
func (m *BooleanValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BooleanValue.Merge(m, src)
}
func (m *BooleanValue) XXX_Size() int {
	return xxx_messageInfo_BooleanValue.Size(m)
}
func (m *BooleanValue) XXX_DiscardUnknown() {
	xxx_messageInfo_BooleanValue.DiscardUnknown(m)
}

var xxx_messageInfo_BooleanValue proto.InternalMessageInfo

func (m *BooleanValue) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func init() {
	proto.RegisterType((*StringValue)(nil), "m18rpc.base.StringValue")
	proto.RegisterType((*BooleanValue)(nil), "m18rpc.base.BooleanValue")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0x2c, 0x4e,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xce, 0x35, 0xb4, 0x28, 0x2a, 0x48, 0xd6, 0x03,
	0x09, 0x29, 0x29, 0x73, 0x71, 0x07, 0x97, 0x14, 0x65, 0xe6, 0xa5, 0x87, 0x25, 0xe6, 0x94, 0xa6,
	0x0a, 0x89, 0x70, 0xb1, 0x96, 0x81, 0x18, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e,
	0x92, 0x0a, 0x17, 0x8f, 0x53, 0x7e, 0x7e, 0x4e, 0x6a, 0x62, 0x1e, 0x16, 0x55, 0x1c, 0x50, 0x55,
	0x4e, 0x2a, 0x51, 0x4a, 0xb9, 0xa5, 0x39, 0x25, 0x99, 0x89, 0x49, 0x39, 0xa9, 0x7a, 0xc9, 0xf9,
	0xb9, 0xfa, 0xe9, 0xf9, 0xfa, 0x10, 0xab, 0xf4, 0x0b, 0xb2, 0xd3, 0xf5, 0xc1, 0x96, 0x27, 0x25,
	0xb1, 0x81, 0x69, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xe7, 0x31, 0xd5, 0x92, 0x00,
	0x00, 0x00,
}
